version: '3.8'

services:
  db:
    image: postgres:15
    container_name: wedding-db
    environment:
      POSTGRES_USER: wedding
      POSTGRES_PASSWORD: wedding123
      POSTGRES_DB: wedding_db
    
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # ⬅️ tambahkan baris ini
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: wedding-backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wedding
      DB_PASSWORD: wedding123
      DB_NAME: wedding_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: wedding-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  db-data:
